version: '3'
services:
 mysql:
  container_name: local_mysql
  image: mysql:5.6.46
  restart: always
  ports:
   - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD:
    MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  volumes: 
   - local-data-volume:/var/lib/mysql
  networks:
   - backend
 warmup:
  build: ./
  container_name: warmup
  restart: always
  ports: 
   - "8080:8080"
  environment:
   DB_HOST: mysql
   DB_PORT: 3306
   DB_SCHEMA: localtest
  depends_on:
   - mysql
  networks:
   - backend
volumes:
 local-data-volume: 
networks:
 backend:
   