spring:
  application:
     name: warmup
  mvc:
   async:
    request-timeout: 5000ms
  data: 
     rest:
        basePath: /
        detection-strategy: annotated
  jpa:
    open-in-view: false
    show_sql: true
    properties:
     hibernate.show_sql: true
     use_sql_comments: true
     format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
  datasource: 
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    port: 3306
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  hibernate:
   dialect: org.hibernate.dialect.MySQLDialect
   show_sql: true

server: 
 port: ${warmup.server.port:8080}
 servlet:
    context-path: /warmup

   
hibernate:
 dialect: org.hibernate.dialect.MySQLDialect     
      
logging:
   level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

